### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by HDVinnie** [surenderssm/MovieBot#1]
This is a really neat bot. Im wondering if and how i can implement this into my current site which is built of laravel. Only issue i see with bot is it posts results twice.

**Comment by surenderssm** [comment]
thank you @HDVinnie for reaching out.
Will look into the issue of results getting posted twice.

"Im wondering if and how i can implement this into my current site which is built of laravel."
If by above statement you mean to reuse the bot in your website. it's very simple it's matter of including the iframe in your html body.

For example you can include following code in your html page to get started.As of now Just add one line/link for the credits which we can include in this repo.md
Let me know if you are looking for any other information.

```

<html>
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <p class="intro-text">
                            <div>Hola ! Glad to see you here, I'm a <a href="https://dev.botframework.com/bots?id=sumalimoviebot">MovieBot</a> @ Powered by <a href="https://botframework.com" target="_blank">Microsoft Bot Framework</a> </div>
                            <div>Please type title/word* of Movie or TV Series you interested in for details.For Eg Titanic or Game*.</div>
                        </p>
                        <div class="divCenter">
                            <iframe src="https://webchat.botframework.com/embed/sumalimoviebot?s=fbri8stOTbQ.cwA.Qgc.HIyNHm0zeZoYnkE4aS_bgyB7tkzkUTZQb8wBMOg_d2M" style="height: 502px; max-height: 502px;"></iframe>
                        </div>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
</header>
</html>
```

**Comment by HDVinnie** [comment]
thanks im interested in using it once double post issue is fixed.
